ALTER TABLE driver_onboarding_tokens
MODIFY id INT NOT NULL AUTO_INCREMENT,
MODIFY driverApplicationId INT NOT NULL,
MODIFY tokenHash VARCHAR(255) NOT NULL,
MODIFY expiresAt DATETIME NOT NULL,
MODIFY usedAt DATETIME NULL,
MODIFY createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

